export const FETCH_DATA = 'FETCH_DATA';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const FETCH_FAILED = 'FETCH_FAILED';

export const GETTING_DATA = 'GETTING_DATA';
export const GETTING_DATA_SUCCESS = 'GETTING_DATA_SUCCESS';
export const GETTING_DATA_FAILED = 'GETTING_DATA_FAILED';

export const GETTING_PERSON = 'GETTING_PERSON';
export const GETTING_PERSON_SUCCESS = 'GETTING_PERSON_SUCCESS';
export const GETTING_PERSON_FAILED = 'GETTING_PERSON_FAILED';

export const GETTING_MOVIES = 'GETTING_MOVIES';
export const GETTING_MOVIES_SUCCESS = 'GETTING_MOVIES_SUCCESS';
export const GETTING_MOVIES_FAILED = 'GETTING_MOVIES_FAILED';

export const GETTING_GENRES = 'GETTING_GENRES';
export const GETTING_GENRES_SUCCESS = 'GETTING_GENRES_SUCCESS';
export const GETTING_GENRES_FAILED = 'GETTING_GENRES_FAILED';

export const GETTING_GENRE_ITEMS = 'GETTING_GENRE_ITEMS';
export const GETTING_GENRE_ITEMS_SUCCESS = 'GETTING_GENRE_ITEMS_SUCCESS';
export const GETTING_GENRE_ITEMS_FAILED = 'GETTING_GENRE_ITEMS_FAILED';

export const GETTING_CURRENT_MOVIE = 'GETTING_CURRENT_MOVIE';
export const GETTING_CURRENT_MOVIE_SUCCESS = 'GETTING_CURRENT_MOVIE_SUCCESS';
export const GETTING_CURRENT_MOVIE_FAILED = 'GETTING_CURRENT_MOVIE_FAILED';

export const GETTING_CONFIG = 'GETTING_CONFIG';
export const GETTING_CONFIG_SUCCESS = 'GETTING_CONFIG_SUCCESS';
export const GETTING_CONFIG_FAILED = 'GETTING_CONFIG_FAILED';

export const GETTING_MOVIES_ERROR = 'GETTING_MOVIES_ERROR';
export const GETTING_GENRES_ERROR = 'GETTING_GENRES_ERROR';

export const MEDIA_REQUEST = 'MEDIA_REQUEST';

export const LOAD_DATA = 'LOAD_DATA';
